"use strict";

module.exports = {
  extends: [
    "stylelint-config-standard",
    "stylelint-config-recommended-scss",
  ],
  plugins: ["stylelint-scss"],
  rules: {
    indentation: 2,
    "max-line-length": 80,
    "string-quotes": ["single", { avoidEscape: true }],
    "font-family-name-quotes": "always-where-recommended",
    "function-url-quotes": "always",
    "number-no-trailing-zeros": true,
    "number-leading-zero": "always",
    "length-zero-no-unit": true,
    "color-named": "never",
    "function-parentheses-space-inside": "never-single-line",
    "value-no-vendor-prefix": true,
    "property-no-vendor-prefix": true,
    "media-feature-name-no-vendor-prefix": true,
    "at-rule-no-vendor-prefix": true,
    "max-nesting-depth": 3,
    "at-rule-empty-line-before": "always",
    "declaration-colon-space-after": "always",
    "declaration-colon-space-before": "never",
    "block-closing-brace-newline-after": "always-multi-line",
    "block-opening-brace-space-before": "always-multi-line",
    "scss/at-else-if-parentheses-space-before": "always",
    "scss/at-else-empty-line-before": "never",
    "scss/at-else-closing-brace-space-after": "always-intermediate",
    "scss/at-else-closing-brace-newline-after": "always-last-in-chain",
    "scss/at-if-no-null": true,
    "scss/at-if-closing-brace-space-after": "always-intermediate",
    "scss/at-if-closing-brace-newline-after": "always-last-in-chain",
    "scss/at-function-pattern": /[a-z\d-]+/,
    "scss/at-mixin-pattern": /[a-z\d-]+/,
    "scss/dollar-variable-pattern": /[a-z\d-]+/,
    "scss/percent-placeholder-pattern": /[a-z\d-]+/,
    "scss/at-mixin-argumentless-call-parentheses": "never",
    "scss/at-mixin-parentheses-space-before": "always",
  },
};
